In [1]:
import numpy as np
import pandas as pd
import category_encoders as ce
import sys, os
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from mpl_toolkits.mplot3d import Axes3D

In [2]:
sys.path.append(os.path.abspath(os.path.join('../scripts')))
from file_handler import FileHandler
from df_selector import *
from df_cleaner import *
from df_visualizer import *
from app_logger import App_Logger

In [3]:
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', 50)

# Reading Data

In [4]:
# create a FileHandler object
file_handler = FileHandler()

In [5]:
# reading the store csv file
df = file_handler.read_csv("../data/lobelia.csv")
df.head(10)

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,views,number_replies,number_forwards,is_forward,forward_msg_from_peer_type,forward_msg_from_peer_id,forward_msg_from_peer_name,forward_msg_date,forward_msg_date_string,forward_msg_link,is_reply,reply_to_msg_id,reply_msg_link,contains_media,media_type,has_url,url,domain,url_title,url_description,document_type,document_id,document_video_duration,document_filename,poll_id,poll_question,poll_total_voters,poll_results,contact_phone_number,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
0,msg_iteration.0.user.lobelia4cosmetics.post.9472,1666492664,lobelia4cosmetics,9472,Multi vitamin Drop \nPrice 2800 birr \nTelegra...,Multi vitamin Drop Price 2800 birr Telegram ht...,2024-06-14 15:40:23+00:00,https://t.me/lobelia4cosmetics/9472,NaN,NaN,824,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,msg_iteration.1.user.lobelia4cosmetics.post.9471,1666492664,lobelia4cosmetics,9471,IRON 365 TABLETS \nPrice 5000 birr \nTelegram ...,IRON 365 TABLETS Price 5000 birr Telegram http...,2024-06-14 13:56:45+00:00,https://t.me/lobelia4cosmetics/9471,NaN,NaN,913,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,msg_iteration.2.user.lobelia4cosmetics.post.9470,1666492664,lobelia4cosmetics,9470,Lilcretters Children Multivitamin \nPrice 4000...,Lilcretters Children Multivitamin Price 4000 b...,2024-06-14 13:56:45+00:00,https://t.me/lobelia4cosmetics/9470,NaN,NaN,793,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,msg_iteration.3.user.lobelia4cosmetics.post.9469,1666492664,lobelia4cosmetics,9469,LAROCHE HYALURONIC ACID SERUM \nPrice 6000 bir...,LAROCHE HYALURONIC ACID SERUM Price 6000 birr ...,2024-06-14 13:56:45+00:00,https://t.me/lobelia4cosmetics/9469,NaN,NaN,605,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,msg_iteration.4.user.lobelia4cosmetics.post.9468,1666492664,lobelia4cosmetics,9468,LAROCHE NIACINAMIDE SERUM \nPrice 6000 birr \n...,LAROCHE NIACINAMIDE SERUM Price 6000 birr Tele...,2024-06-14 13:56:45+00:00,https://t.me/lobelia4cosmetics/9468,NaN,NaN,616,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,msg_iteration.5.user.lobelia4cosmetics.post.9467,1666492664,lobelia4cosmetics,9467,LAROCHE VITAMIN C SERUM \nPrice 6000 birr \nTe...,LAROCHE VITAMIN C SERUM Price 6000 birr Telegr...,2024-06-14 13:56:45+00:00,https://t.me/lobelia4cosmetics/9467,NaN,NaN,640,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,msg_iteration.6.user.lobelia4cosmetics.post.9466,1666492664,lobelia4cosmetics,9466,DHA DROP \nPrice 3600 birr \nTelegram https://...,DHA DROP Price 3600 birr Telegram https://t.me...,2024-06-14 10:56:27+00:00,https://t.me/lobelia4cosmetics/9466,NaN,NaN,902,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,msg_iteration.7.user.lobelia4cosmetics.post.9465,1666492664,lobelia4cosmetics,9465,WELL KID CALCIUM SYRUP \nPrice 3200 birr \nTel...,WELL KID CALCIUM SYRUP Price 3200 birr Telegra...,2024-06-14 10:56:27+00:00,https://t.me/lobelia4cosmetics/9465,NaN,NaN,835,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,msg_iteration.8.user.lobelia4cosmetics.post.9464,1666492664,lobelia4cosmetics,9464,Peppa Pig Vitamin D3 Gummies \nPrice 2600 birr...,Peppa Pig Vitamin D3 Gummies Price 2600 birr T...,2024-06-14 10:56:27+00:00,https://t.me/lobelia4cosmetics/9464,NaN,NaN,602,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,msg_iteration.9.user.lobelia4cosmetics.post.9463,1666492664,lobelia4cosmetics,9463,WELL KID Multivitamin with D3 \nPrice 2600 bir...,WELL KID Multivitamin with D3 Price 2600 birr ...,2024-06-14 10:56:27+00:00,https://t.me/lobelia4cosmetics/9463,NaN,NaN,516,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# General Statistics

In [7]:
df.size

163807

In [8]:
df.shape

(3343, 49)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3343 entries, 0 to 3342
Data columns (total 49 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   signature                   3343 non-null   object
 1   channel_id                  3343 non-null   int64
 2   channel_name                3343 non-null   object
 3   msg_id                      3343 non-null   int64
 4   message                     2983 non-null   object
 5   cleaned_message             2983 non-null   object
 6   date                        3343 non-null   object
 7   msg_link                    3343 non-null   object
 8   msg_from_peer               0 non-null      float64
 9   msg_from_id                 0 non-null      float64
 10  views                       3343 non-null   int64
 11  number_replies              3343 non-null   int64
 12  number_forwards             3343 non-null   int64
 13  is_forward                  3343 non-null   int64
 14  forward_msg_from_peer_type  4 non-null      object
 15  forward_msg_from_peer_id    4 non-null      float64
 16  forward_msg_from_peer_name  4 non-null      object
 17  forward_msg_date            4 non-null      object
 18  forward_msg_date_string     4 non-null      object
 19  forward_msg_link            4 non-null      object
 20  is_reply                    3343 non-null   int64
 21  reply_to_msg_id             9 non-null      float64
 22  reply_msg_link              9 non-null      object
 23  contains_media              3343 non-null   int64
 24  media_type                  3343 non-null   object
 25  has_url                     3343 non-null   int64
 26  url                         2 non-null      object
 27  domain                      2 non-null      object
 28  url_title                   2 non-null      object
 29  url_description             2 non-null      object
 30  document_type               1 non-null      object
 31  document_id                 1 non-null      float64
 32  document_video_duration     0 non-null      float64
 33  document_filename           1 non-null      object
 34  poll_id                     0 non-null      float64
 35  poll_question               0 non-null      float64
 36  poll_total_voters           0 non-null      float64
 37  poll_results                0 non-null      float64
 38  contact_phone_number        0 non-null      float64
 39  contact_name                0 non-null      float64
 40  contact_userid              0 non-null      float64
 41  geo_type                    0 non-null      float64
 42  lat                         0 non-null      float64
 43  lng                         0 non-null      float64
 44  venue_id                    0 non-null      float64
 45  venue_type                  0 non-null      float64
 46  venue_title                 0 non-null      float64
 47  venue_address               0 non-null      float64
 48  venue_provider              0 non-null      float64
dtypes: float64(21), int64(9), object(19)
memory usage: 1.2+ MB

# Missing Values

In [10]:
percent_missing_values(df)

The dataset contains 67.75 % missing values.

In [11]:
missing_df = missing_values_table(df)

Your selected dataframe has 49 columns.
There are 35 columns that have missing values.

In [12]:
df = df.dropna(how='all',axis=1)

In [13]:
df.shape

(3343, 31)

In [14]:
missing_df

                            Missing Values  % of Total Values    Dtype
venue_provider                        3343             100.00  float64
geo_type                              3343             100.00  float64
poll_id                               3343             100.00  float64
poll_question                         3343             100.00  float64
poll_total_voters                     3343             100.00  float64
poll_results                          3343             100.00  float64
contact_phone_number                  3343             100.00  float64
contact_name                          3343             100.00  float64
contact_userid                        3343             100.00  float64
lat                                   3343             100.00  float64
lng                                   3343             100.00  float64
venue_id                              3343             100.00  float64
venue_type                            3343             100.00  float64
venue_title                           3343             100.00  float64
venue_address                         3343             100.00  float64
msg_from_id                           3343             100.00  float64
msg_from_peer                         3343             100.00  float64
document_video_duration               3343             100.00  float64
document_filename                     3342              99.97   object
document_id                           3342              99.97  float64
document_type                         3342              99.97   object
url_description                       3341              99.94   object
url_title                             3341              99.94   object
domain                                3341              99.94   object
url                                   3341              99.94   object
forward_msg_link                      3339              99.88   object
forward_msg_date_string               3339              99.88   object
forward_msg_date                      3339              99.88   object
forward_msg_from_peer_name            3339              99.88   object
forward_msg_from_peer_id              3339              99.88  float64
forward_msg_from_peer_type            3339              99.88   object
reply_msg_link                        3334              99.73   object
reply_to_msg_id                       3334              99.73  float64
cleaned_message                        360              10.77   object
message                                360              10.77   object

In [15]:
count_missing_rows(df)

3343 rows(100.0%) contain atleast one missing value.

In [16]:
# dataframe containing the missing rows for columns in group 1
group1_df = df[df['forward_msg_link'].isna()]
group1_df.head(10)

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,views,number_replies,number_forwards,is_forward,forward_msg_from_peer_type,forward_msg_from_peer_id,forward_msg_from_peer_name,forward_msg_date,forward_msg_date_string,forward_msg_link,is_reply,reply_to_msg_id,reply_msg_link,contains_media,media_type,has_url,url,domain,url_title,url_description,document_type,document_id,document_filename
0,msg_iteration.0.user.lobelia4cosmetics.post.9472,1666492664,lobelia4cosmetics,9472,Multi vitamin Drop \nPrice 2800 birr \nTelegra...,Multi vitamin Drop Price 2800 birr Telegram ht...,2024-06-14 15:40:23+00:00,https://t.me/lobelia4cosmetics/9472,824,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,msg_iteration.1.user.lobelia4cosmetics.post.9471,1666492664,lobelia4cosmetics,9471,IRON 365 TABLETS \nPrice 5000 birr \nTelegram ...,IRON 365 TABLETS Price 5000 birr Telegram http...,2024-06-14 13:56:45+00:00,https://t.me/lobelia4cosmetics/9471,913,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,msg_iteration.2.user.lobelia4cosmetics.post.9470,1666492664,lobelia4cosmetics,9470,Lilcretters Children Multivitamin \nPrice 4000...,Lilcretters Children Multivitamin Price 4000 b...,2024-06-14 13:56:45+00:00,https://t.me/lobelia4cosmetics/9470,793,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,msg_iteration.3.user.lobelia4cosmetics.post.9469,1666492664,lobelia4cosmetics,9469,LAROCHE HYALURONIC ACID SERUM \nPrice 6000 bir...,LAROCHE HYALURONIC ACID SERUM Price 6000 birr ...,2024-06-14 13:56:45+00:00,https://t.me/lobelia4cosmetics/9469,605,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,msg_iteration.4.user.lobelia4cosmetics.post.9468,1666492664,lobelia4cosmetics,9468,LAROCHE NIACINAMIDE SERUM \nPrice 6000 birr \n...,LAROCHE NIACINAMIDE SERUM Price 6000 birr Tele...,2024-06-14 13:56:45+00:00,https://t.me/lobelia4cosmetics/9468,616,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,msg_iteration.5.user.lobelia4cosmetics.post.9467,1666492664,lobelia4cosmetics,9467,LAROCHE VITAMIN C SERUM \nPrice 6000 birr \nTe...,LAROCHE VITAMIN C SERUM Price 6000 birr Telegr...,2024-06-14 13:56:45+00:00,https://t.me/lobelia4cosmetics/9467,640,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,msg_iteration.6.user.lobelia4cosmetics.post.9466,1666492664,lobelia4cosmetics,9466,DHA DROP \nPrice 3600 birr \nTelegram https://...,DHA DROP Price 3600 birr Telegram https://t.me...,2024-06-14 10:56:27+00:00,https://t.me/lobelia4cosmetics/9466,902,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,msg_iteration.7.user.lobelia4cosmetics.post.9465,1666492664,lobelia4cosmetics,9465,WELL KID CALCIUM SYRUP \nPrice 3200 birr \nTel...,WELL KID CALCIUM SYRUP Price 3200 birr Telegra...,2024-06-14 10:56:27+00:00,https://t.me/lobelia4cosmetics/9465,835,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,msg_iteration.8.user.lobelia4cosmetics.post.9464,1666492664,lobelia4cosmetics,9464,Peppa Pig Vitamin D3 Gummies \nPrice 2600 birr...,Peppa Pig Vitamin D3 Gummies Price 2600 birr T...,2024-06-14 10:56:27+00:00,https://t.me/lobelia4cosmetics/9464,602,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,msg_iteration.9.user.lobelia4cosmetics.post.9463,1666492664,lobelia4cosmetics,9463,WELL KID Multivitamin with D3 \nPrice 2600 bir...,WELL KID Multivitamin with D3 Price 2600 birr ...,2024-06-14 10:56:27+00:00,https://t.me/lobelia4cosmetics/9463,516,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1,MessageMediaPhoto,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# all unique values for each column
unique_values_df(group1_df)

,Column,Unique values
0,signature,[msg_iteration.0.user.lobelia4cosmetics.post.9...
1,channel_id,[1666492664]
2,channel_name,[lobelia4cosmetics]
3,msg_id,"[9472, 1359, 1440, 1439, 1438, 1437, 1436, 143..."
4,message,[Price 1800 birr \nTelegram https://t.me/lobel...
5,cleaned_message,[Price 1800 birr Telegram https://t.me/lobelia...
6,date,"[2024-03-30 07:08:58+00:00, 2024-03-30 07:08:5..."
7,msg_link,"[https://t.me/lobelia4cosmetics/9472, https://..."
8,views,"[4598, 5167, 3507, 4703, 4671, 4650, 4655, 405..."
9,number_replies,[0]
10,number_forwards,"[1, 2, 0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 14, 12,..."
11,is_forward,[0]
12,forward_msg_from_peer_type,[]
13,forward_msg_from_peer_id,[]
14,forward_msg_from_peer_name,[]
15,forward_msg_date,[]
16,forward_msg_date_string,[]
17,forward_msg_link,[]
18,is_reply,"[0, 1]"
19,reply_to_msg_id,"[2515.0, 2390.0, 2300.0, 2250.0, 2215.0, 2198...."
20,reply_msg_link,"[https://t.me/lobelia4cosmetics/2515, https://..."
21,contains_media,[1]
22,media_type,"[MessageMediaPhoto, MessageMediaWebPage, Messa..."
23,has_url,"[0, 1]"
24,url,[https://t.me/lobelia4cosmetics]
25,domain,[t.me]
26,url_title,[Lobelia pharmacy and cosmetics]
27,url_description,[American and Canadian Genuine products]
28,document_type,[image/gif]
29,document_id,[5.931259804671544e+18]
30,document_filename,[animation.gif]

In [18]:
fix_missing_value(df, ['forward_msg_from_peer_type', 'forward_msg_from_peer_id','forward_msg_from_peer_name','forward_msg_date','forward_msg_date_string','forward_msg_link'], 0)

3339 missing values in the column forward_msg_from_peer_type have been replaced by 0.
3339 missing values in the column forward_msg_from_peer_id have been replaced by 0.
3339 missing values in the column forward_msg_from_peer_name have been replaced by 0.
3339 missing values in the column forward_msg_date have been replaced by 0.
3339 missing values in the column forward_msg_date_string have been replaced by 0.
3339 missing values in the column forward_msg_link have been replaced by 0.

In [20]:
fix_missing_value(df, ['url', 'domain','url_title','url_description','document_type','document_id','document_filename','media_type'], 0)

0 missing values in the column url have been replaced by 0.
0 missing values in the column domain have been replaced by 0.
0 missing values in the column url_title have been replaced by 0.
0 missing values in the column url_description have been replaced by 0.
0 missing values in the column document_type have been replaced by 0.
0 missing values in the column document_id have been replaced by 0.
3342 missing values in the column document_filename have been replaced by 0.
0 missing values in the column media_type have been replaced by 0.

In [23]:
fix_missing_value(df, ['has_url', 'contains_media','reply_msg_link','reply_to_msg_id'], 0)

0 missing values in the column has_url have been replaced by 0.
0 missing values in the column contains_media have been replaced by 0.
3334 missing values in the column reply_msg_link have been replaced by 0.
3334 missing values in the column reply_to_msg_id have been replaced by 0.

In [21]:
fix_missing_value(df, ['message', 'cleaned_message'], 0)

360 missing values in the column message have been replaced by 0.
360 missing values in the column cleaned_message have been replaced by 0.

In [24]:
percent_missing_values(df)

The dataset contains 0.0 % missing values.

# Data Types

In [25]:
show_cols_mixed_dtypes(df)

                        Column      Data type
0                      message  mixed-integer
1              cleaned_message  mixed-integer
2   forward_msg_from_peer_type  mixed-integer
3   forward_msg_from_peer_name  mixed-integer
4             forward_msg_date  mixed-integer
5      forward_msg_date_string  mixed-integer
6             forward_msg_link  mixed-integer
7               reply_msg_link  mixed-integer
8                          url  mixed-integer
9                       domain  mixed-integer
10                   url_title  mixed-integer
11             url_description  mixed-integer
12               document_type  mixed-integer
13           document_filename  mixed-integer

In [26]:
df.dtypes

signature                      object
channel_id                      int64
channel_name                   object
msg_id                          int64
message                        object
cleaned_message                object
date                           object
msg_link                       object
views                           int64
number_replies                  int64
number_forwards                 int64
is_forward                      int64
forward_msg_from_peer_type     object
forward_msg_from_peer_id      float64
forward_msg_from_peer_name     object
forward_msg_date               object
forward_msg_date_string        object
forward_msg_link               object
is_reply                        int64
reply_to_msg_id               float64
reply_msg_link                 object
contains_media                  int64
media_type                     object
has_url                         int64
url                            object
domain                         object
url_title                      object
url_description                object
document_type                  object
document_id                   float64
document_filename              object
dtype: object

In [27]:
# get the columns with object data type
string_columns = df.select_dtypes(include='object').columns.tolist()
string_columns

['signature',
 'channel_name',
 'message',
 'cleaned_message',
 'date',
 'msg_link',
 'forward_msg_from_peer_type',
 'forward_msg_from_peer_name',
 'forward_msg_date',
 'forward_msg_date_string',
 'forward_msg_link',
 'reply_msg_link',
 'media_type',
 'url',
 'domain',
 'url_title',
 'url_description',
 'document_type',
 'document_filename']

In [28]:
convert_to_string(df, string_columns)

In [29]:
convert_to_datetime(df, ['date'])

In [30]:
show_cols_mixed_dtypes(df)

None of the columns contain mixed types.

In [31]:
df.dtypes

signature                          string[python]
channel_id                                  int64
channel_name                       string[python]
msg_id                                      int64
message                            string[python]
cleaned_message                    string[python]
date                          datetime64[ns, UTC]
msg_link                           string[python]
views                                       int64
number_replies                              int64
number_forwards                             int64
is_forward                                  int64
forward_msg_from_peer_type         string[python]
forward_msg_from_peer_id                  float64
forward_msg_from_peer_name         string[python]
forward_msg_date                   string[python]
forward_msg_date_string            string[python]
forward_msg_link                   string[python]
is_reply                                    int64
reply_to_msg_id                           float64
reply_msg_link                     string[python]
contains_media                              int64
media_type                         string[python]
has_url                                     int64
url                                string[python]
domain                             string[python]
url_title                          string[python]
url_description                    string[python]
document_type                      string[python]
document_id                               float64
document_filename                  string[python]
dtype: object

# Duplicates

In [32]:
# search for duplicate rows and drop them
drop_duplicates(df)

No duplicate rows were found.

In [33]:
df.duplicated(subset=['signature']).all()

False

In [34]:
file_handler.to_csv(df, '../data/new/lobelia.csv')